---
- name: Fail if required variables are not defined
  assert:
    that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
  loop:
    - nginx_controller_fqdn
    - nginx_controller_auth_token
    - nginx_controller_environmentName
    - nginx_controller_certificate.metadata.name
    - nginx_controller_certificate.desiredState.type

- name: Form the certificate API url
  set_fact:
    nginx_controller_certificate_url: "https://{{ nginx_controller_fqdn }}/{{ nginx_controller_api_version }}/services/environments/{{ nginx_controller_environmentName }}/certs/{{ nginx_controller_certificate.metadata.name }}"

- name: Upsert certificate (create if absent, change if present)
  uri:
    url: "{{ nginx_controller_certificate_url }}"
    method: "PUT"
    body: "{{ nginx_controller_certificate }}"
    body_format: json
    status_code:
      - 200
      - 201
      - 202
    return_content: true
    validate_certs: "{{ nginx_controller_validate_certs | default(false) }}"
    headers:
      Cookie: "{{ nginx_controller_auth_token }}"
  register: nginx_controller_certificate_status

- name: Show certificate status
  debug:
    msg: "{{ nginx_controller_certificate_status }}"

- name: Pause while system initiates changes
  pause:
    seconds: 2

- name: Confirm certificate is provisioned and not errored
  uri:
    url: "{{ nginx_controller_certificate_url }}"
    method: "GET"
    body_format: json
    status_code:
      - 200
    return_content: true
    validate_certs: "{{ nginx_controller_validate_certs | default(false) }}"
    headers:
      Cookie: "{{ nginx_controller_auth_token }}"
  register: nginx_controller_certificate_status
  until: (nginx_controller_certificate_status is defined) and
         (nginx_controller_certificate_status.json.currentStatus.state.selfConfigState.isConfigured | bool)
  retries: 10
  delay: 2
  failed_when: nginx_controller_certificate_status.json.currentStatus.state.selfConfigState.isError | bool

- name: Capture certificate reference
  set_fact:
    nginx_controller_certificate_reference: "{{ nginx_controller_certificate_status.json.metadata.links.rel }}"

- name: Show certificate reference
  debug:
    msg: "{{ nginx_controller_certificate_reference }}"
