---
- name: Converge
  hosts: all

  vars:
    # controller:
    #   user_email: "user@example.com"
    #   user_password: "mySecurePassword"
    #   fqdn: "controller.mydomain.com"
    #   validate_certs: false
    #
    # environmentName: ""
    # certificate:
    #   metadata:
    #     name: "www.example.com"
    #     displayName: "Root WWW Cert"
    #     description: "A certificate"
    #   desiredState:
    #     type: "PEM"
    #     privateKey: ""
    #     publicCert: ""

  tasks:
    - include_role:
        name: ansible-role-nginx-controller-certificate
